### ISSUE TITLE
Can't load background image

### ISSUE THREAD

**Issue by iloverails** [webrecorder/wabac.js#108] opened 2023-02-16 17:48 UTC
In the attached archive `.content-panel5` sections not loaded on the page. Here is original site https://gyazo.com/8f399620010187f41f47a774ed34f92c?token=988954ea99da590383deba5825f9c27c and this is an archived version https://gyazo.com/bd207b3bcf4a091b6d5780835d0d9063 of that page. So you can that first section doesn't exist in the archived version. Here is missed html https://gyazo.com/14af490072cf968dfd106195c553c89d 

I started investigation and found that section removed if background image loading process is failed https://gyazo.com/7fa6fe2abcad58ff20c0acbe4d915558.  But when I checked network tab I found that image loaded with status 200. So could you help to understand why background images are failed?

Here is archive https://drive.google.com/file/d/1ou88yZBuqNme3_xd8Z52extiMJbOxpTa/view?usp=share_link

**Comment by iloverails** [comment] 2023-02-17 14:28
I more investigated it and found the reason of why some contents are not loaded for that archive. The archive pages consist of blocks which are lazy loaded dynamically from API (it’s called Articles) and if any block data has background image then that image loading status observed via ImageObserver. Here is code:
```
this.view.imageObserver.observe(),
this.view.bgImageObserver = (0,
    r.default)(".lozad-bg-image", {
    loaded: function(e) {
        l(e).parent().imagesLoaded({
            background: ".bg-image"
        }, function() {}).done(function() {
            e.style.opacity = 1,
                o.channel("global:dashboard:isotope").trigger("layout", e)
        }).fail(function() {
            e.style.display = "none",
                l(e).remove(),
                o.channel("global:dashboard:isotope").trigger("layout", e)
        })
    }
})
```
and in case if image was failed than whole container deleted (pretty strange logic though) l(e).remove(), 
I checked image status and found it has status 200 [Screenshot by Gyazo](https://gyazo.com/1cbeb4dcb09b489b3029c0bd4da94e9a)  But by some reason it is recognized as failed when we load it under Wabac dom.
I found how to hard fix it, need to add this rule
```
[/e\.style\.display="none",l\(e\)\.remove\(\)/g, replace('e.style.display="none",l(e).remove()', 'e.style.opacity=1')]
```
to jsrewriter.js , but that is hardcode.

**Comment by ikreymer** [comment] 2023-02-26 00:43
Thanks for helping debug this!
There were several issues, one was the fuzzy matching was too aggressive with the .json file - not sure if you changed anything in your config, so it was loading the wrong file initially?
The second issue, which you've identified above, was caused by `CSSStyleDeclaration.backgroundImage` returning the rewritten URL instead of the original. This was causing the image to be marked as failed. Fixing that in wombat.js (webrecorder/wombat#113) fixes that issue, so no custom rules are needed.

It should now work in replayweb.page 1.7.13 and up.

**Closed by ikreymer** 2023-02-26 00:43 UTC
